apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadbalancer-app
  template:
    metadata:
      labels:
        app: loadbalancer-app
    spec:
      containers:
      - name: my-container
        image: 178502901196.dkr.ecr.us-east-1.amazonaws.com/cicdpipeline:IMAGE_TAG
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: loadbalancer-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

